### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by VoidableMoon884** [animegasan/luci-app-gpioled#1]
How I can install it on Luci OpenWrt on a RaspberryPi?
I tried it with this URL: https://github.com/animegasan/luci-app-gpioled/archive/refs/heads/main.zip but it didn't work.

**Comment by animegasan** [comment]
> How I can install it on Luci OpenWrt on a RaspberryPi? I tried it with this URL: https://github.com/animegasan/luci-app-gpioled/archive/refs/heads/main.zip but it didn't work.

Isn't the installation method using the IPK file instead of zip?

**Comment by animegasan** [comment]
Isn't the LED on RaspberryPi already registered in the openwrt kernel?

What version of RaspberryPi?

**Comment by VoidableMoon884** [comment]
RaspberryPi 3b.
The default LEDs are already registered.
But I will add more LEDs via gpio.

**Comment by VoidableMoon884** [comment]
![IMG_0033](https://github.com/animegasan/luci-app-gpioled/assets/87603556/5caa7255-f226-49a2-86e7-fb20a18c2a7f)

**Comment by animegasan** [comment]
Try changing one of the envs in `/usr/share/gpioled/env` file in the section

```js
if [ "$DEVICE" = "HG680PR1" ]; then
    GPWR1=483
    GPWR2=484
    GETH1=481
    GETH2=482
    GIRB=480
elif [ "$DEVICE" = "HG680PR2" ]; then
    GPWR1=425
    GPWR2=426
    GETH1=506
    GETH2=510
    GIRB=507
fi
```
Because I haven't been able to adjust the different gpio leds

**Comment by animegasan** [comment]
Because everything refers to the env

**Comment by VoidableMoon884** [comment]
Is anywhere a ipk file?
Then I can try it with the ipk file.

**Comment by animegasan** [comment]
Yes, it is in the ipk file. Try installing now

**Comment by VoidableMoon884** [comment]
Sorry, but can u give me instructions how to build the ipk File?

**Comment by animegasan** [comment]
> Sorry, but can u give me instructions how to build the ipk File?

Try this link
[Using SDK](https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk)
[Package](https://openwrt.org/docs/guide-developer/packages)

**Comment by VoidableMoon884** [comment]
The following error occurred: make: *** No rule to make target '/feeds/luci/luci.mk'
Now I have removed the line "include $(TOPDIR)/feeds/luci/luci.mk". Now the rules.mk file cannot be found.
If I also remove this line ("include $(TOPDIR)/rules.mk"), it cannot find a target.

**Comment by animegasan** [comment]
Maybe this can help.

1. Download the SDK
2. Extract the SDK file and enter it into the folder
3. Run feeds update
```./scripts/feeds update -a```
4. Git clone this repository to folder package 
```git clone https://github.com/animegasan/luci-app-gpioled/ package/luci-app-gpioled```
5. Edit file on your coding
6. Compile code to ipk in SDK folder
```make package/luci-app-gpioled/compile```

**Comment by VoidableMoon884** [comment]
Thankyou very much.
I will try it.
